#!/bin/bash
# local-vars
#
# This file contains default connexion informations,
# some informations (like database connexion variables) should be overrided
# in a local-vars file.
# Ce fichier contient les infos de connexion par défaut,
# certaines de ces informations (comme les accès à la BDD) devraient être
# surchargées dans un fichier local-vars.
#

################################
# Apache user/group            #
################################
APACHE=www-data

################################
# Useful folders               #
################################
WORKSPACE=`pwd`
DRUPAL_ROOT=$WORKSPACE/src/drupal
DRUSH_ALIASES=$DRUPAL_ROOT/sites/all/drush

################################
# Password for MySQL root user #
################################
MYSQL_PASS="mysqlrootpass"

################################
# Informations for MySQL user  #
# & website database           #
################################
DB_USER="drupal_user"
DB_PASS="drupal_pass"
DB_NAME="drupal_database"

################################
# Drupal site name             #
################################
SITE_NAME="Drupal app"

################################
# Drupal administrator account #
################################
SITE_ADMIN_NAME="admin"
SITE_ADMIN_PASS="admin"

################################
# Drupal default environment   #
################################
SITE_ENVIRONMENT=local

################################
# Drupal install profile       #
################################
SITE_PROFILE="standard"

################################
# Makefile name                #
################################
MAKEFILE="fromages"

################################
# Custom projects location     #
################################
PROJECTS_LOCATION=""
