#!/bin/sh
# site-update
#
# Script de mise à jour d'un site
#
# Pour mettre à jour un site :
# - modifier le fichier .make du profil d'installation
# - ./site-update

# Stop on error
set -e

echo ' ___   ___   ___'
echo '|___| |   | |   |'
echo ' ___  |   | |___|'
echo '|   | |   |  ___ '
echo '|   | |___| |___|'
echo '|   |  _________ '
echo '|___| |_________|'
echo ''
echo '================='
echo '  Fromages       '
echo '================='

# call default vars
. `pwd`/default-vars

# and override with local vars
FILE="local-vars"
if [ -f $FILE ];
then
  . $WORKSPACE/$FILE
else
  echo "File $FILE does not exist, used default values."
fi

cd $DRUPAL_ROOT

echo "\nThis command can be used to rebuild the installation profile in place. Be careful as it will wipe out contrib and custom modules.\n"
echo "  [1] Rebuild profile in place in release mode (latest stable release)"
# echo "  [2] Rebuild profile in place in development mode (latest dev code)"
echo "  [2] Rebuild profile in place in development mode (latest dev code with .git working-copy)\n"
echo "Selection: \c"
read SELECTION

if [ $SELECTION = "1" ]; then

  echo "Building Tatooine install profile in release mode..."
  drush make --no-gitinfofile $WORKSPACE/build/$MAKEFILE.make .

elif [ $SELECTION = "2" ]; then

  echo "Building Tatooine install profile in development mode (latest dev code with .git working-copy)"
  drush make --working-copy --no-gitinfofile $WORKSPACE/build/$MAKEFILE.make .

else
 echo "Invalid selection."
 exit 0
fi

# # Get site environment
# DRUPAL_ENV=`drush vget environment --format=string`
# echo 'Environment to be deployed: '$DRUPAL_ENV

# # Copy environment settings file from source repository to Drupal folder
# cp $WORKSPACE/deploy/env/settings.$DRUPAL_ENV.php $DRUPAL_ROOT/sites/default/settings.$DRUPAL_ENV.php
# echo "Update environment settings file settings.$DRUPAL_ENV.php"

# # Apply environment configuration
# drush d-conf

# Apply hook_update_N()
drush updb -y

# Revert features just to be sure
drush fra -y

# Clear all cache
drush cc all

exit 0;
