#!/bin/bash
# site-update
#
# Script de mise à jour d'un site
#
# Pour mettre à jour un site :
# - modifier le fichier .make du profil d'installation
# - ./site-update

# Stop on error
set -e

# Define colors
RED="\e[00;31m"
YELLOW="\e[01;33m"
GREEN="\e[00;32m"
NOCOLOR="\e[00m"

# Get informations to build site
SITE_TO_BUILD=$1
if [ -z "$1" ]; then
  echo -e "${RED}You must pass a site to build as first parameter.${NOCOLOR}"
  exit 0;
fi

# Display ASCII Cheese
echo ""
echo -e "${YELLOW}     _--'-.           ${NOCOLOR}"
echo -e "${YELLOW}  .-'      '-.        ${NOCOLOR}"
echo -e "${YELLOW} |''--..      '-.     ${NOCOLOR}"
echo -e "${YELLOW} |      ''--..   '-.  ${NOCOLOR}"
echo -e "${YELLOW} |.-. .-'.    ''--..'.${NOCOLOR}"
echo -e "${YELLOW} |'./  -_'  .-.      |${NOCOLOR}"
echo -e "${YELLOW} |      .-. '.-'   .-'${NOCOLOR}"
echo -e "${YELLOW} '--..  '.'    .-  -. ${NOCOLOR}"
echo -e "${YELLOW}      ''--..   '_'   :${NOCOLOR}"
echo -e "${YELLOW}            ''--..   |${NOCOLOR}"
echo -e "${YELLOW}                  ''-'${NOCOLOR}"
echo ""
echo "======================"
echo "==     Fromages     =="
echo "======================"

# call default vars
. `pwd`/vars/default

# and override with local vars
FILE=vars/$SITE_TO_BUILD
if [ -f $FILE ]; then
  . $WORKSPACE/$FILE
else
  echo -e "${YELLOW}File $FILE does not exist, used default values.${NOCOLOR}"
fi

cd $DRUPAL_ROOT

echo "This command can be used to rebuild the installation profile in place. Be careful as it will wipe out contrib and custom modules."
echo "  [1] Rebuild profile in place in release mode (latest stable release)"
# echo "  [2] Rebuild profile in place in development mode (latest dev code)"
echo "  [2] Rebuild profile in place in development mode (latest dev code with .git working-copy)"
echo "Selection:"
read SELECTION

if [ $SELECTION = "1" ]; then
  echo -e "${GREEN}Building Tatooine install profile in release mode...${NOCOLOR}"
  drush make --no-gitinfofile $WORKSPACE/build/$MAKEFILE.make .
elif [ $SELECTION = "2" ]; then
  echo -e "${GREEN}Building Tatooine install profile in development mode (latest dev code with .git working-copy)...${NOCOLOR}"
  drush make --working-copy --no-gitinfofile $WORKSPACE/build/$MAKEFILE.make .
else
 echo -e "${RED}Invalid selection.${NOCOLOR}"
  exit 0
fi

# # Get site environment
# DRUPAL_ENV=`drush vget environment --format=string`
# echo 'Environment to be deployed: '$DRUPAL_ENV

# # Copy environment settings file from source repository to Drupal folder
# cp $WORKSPACE/deploy/env/settings.$DRUPAL_ENV.php $DRUPAL_ROOT/sites/default/settings.$DRUPAL_ENV.php
# echo "Update environment settings file settings.$DRUPAL_ENV.php"

# # Apply environment configuration
# drush d-conf

# Apply hook_update_N()
drush updb -y

# Revert features just to be sure
drush fra -y

# Clear all cache
drush cc all

exit 0;
