#!/bin/bash
# local-vars
#
# This file contains default connexion informations,
# some informations (like database connexion variables) should be overrided
# in a local-vars file.
# Ce fichier contient les infos de connexion par défaut,
# certaines de ces informations (comme les accès à la BDD) devraient être
# surchargées dans un fichier local-vars.
#

################################
# Informations for MySQL user  #
# & website database           #
################################
DB_USER="indus_demo"
DB_PASS="WNsqQumayJVZHrLC"
DB_NAME="indus_demo"

################################
# Drupal site name             #
################################
SITE_NAME="DrupalCamp MTL 12"

################################
# Drupal administrator account #
################################
SITE_ADMIN_NAME="admin"
SITE_ADMIN_PASS="admin"

################################
# Drupal install profile       #
################################
SITE_PROFILE="indus_profile"
PROFILE_REPO="git@github.com:sfl-drupal/indus-profile.git"

################################
# Makefile name                #
################################
MAKEFILE="demo"

################################
# Custom module                #
################################
CUSTOM_MODULE="indus_core"
